
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://awozvespcrnfkfkpoyft.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF3b3p2ZXNwY3JuZmtma3BveWZ0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE0MTE0MzMsImV4cCI6MjA1Njk4NzQzM30.GKwIBSn11_eHA6tQejORganVvGMalZMzUfi9hgh9XdA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Use a more generic type for now to avoid type errors with table names
type GenericDatabase = Database & {
  public: {
    Tables: {
      vaya_families: any;
      vaya_family_members: any;
      vaya_memories: any;
      vaya_stories: any;
      vaya_photos: any;
      vaya_bookmarks: any;
      vaya_localized_prompts: any;
      vaya_capsule_schedules: any;
      capsule_schedules: any;
      profiles: {
        Row: {
          id: string;
          full_name: string;
          avatar_url: string | null;
          updated_at: string | null;
          created_at: string | null;
          preferred_language?: string;
        };
        Insert: {
          id: string;
          full_name: string;
          avatar_url?: string | null;
          updated_at?: string | null;
          created_at?: string | null;
          preferred_language?: string;
        };
        Update: {
          id?: string;
          full_name?: string;
          avatar_url?: string | null;
          updated_at?: string | null;
          created_at?: string | null;
          preferred_language?: string;
        };
      };
    };
  };
};

export const supabase = createClient<GenericDatabase>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
