// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://awozvespcrnfkfkpoyft.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF3b3p2ZXNwY3JuZmtma3BveWZ0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE0MTE0MzMsImV4cCI6MjA1Njk4NzQzM30.GKwIBSn11_eHA6tQejORganVvGMalZMzUfi9hgh9XdA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);